import Head from "next/head";
import React, { Fragment, useState } from "react";
import Footer from "./Footer";
import Header from "./Header";
import Sidebar from "./Sidebar";

const LayoutDashboard = ({children, title="Sample Title"}) => {
     //console.log("layout", title)
     const [mobileNavsidebar, setMobileNavsidebar] = useState(false);
     


  return (
    <Fragment>
      
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <div className="relative flex min-h-screen bg-gray-100">
        
          <Sidebar />
          
          <div className="flex-grow text-gray-800">
          <Header mobileNavsidebar={mobileNavsidebar} setMobileNavsidebar={setMobileNavsidebar} />
              {children}
          </div>

        <Footer />
      </div> 
        

    </Fragment>
  );
};

export default LayoutDashboard;
